# Generated by Django 4.2.6 on 2023-10-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='is_digital',
        ),
    ]
