# Generated by Django 4.2.6 on 2023-10-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productinventory_is_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='attribute_values',
        ),
    ]
