# Generated by Django 4.2.6 on 2023-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_productinventory_attribute_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='attribute_values',
            field=models.ManyToManyField(related_name='product_attribute_values', through='inventory.ProductAttributeValues', to='inventory.productattributevalue'),
        ),
    ]
